linters:
  enable-all: true
  disable:
    - exportloopref
    - forbidigo
    - ireturn
    - nlreturn
    - wsl
linters-settings:
  gci:
    sections:
      - standard
      - localmodule
      - default
    custom-order: true
