linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - err113
    - exportloopref
    - forbidigo
    - ireturn
    - mnd
    - nlreturn
    - nosprintfhostport
    - varnamelen
    - wsl
linters-settings:
  gci:
    sections:
      - standard
      - localmodule
      - default
    custom-order: true
  gofumpt:
    module-path: morbo
  lll:
    line-length: 125
