# Copyright (C) 2024 Pavel Sobolev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: morbo
services:
  backend:
    build: .
    image: ghcr.io/morbo-org/backend:latest
    environment:
      - MORBO_DB_HOST=db
      - MORBO_DB_PORT=5432
      - MORBO_DB_USER=morbo
      - MORBO_DB_PASSWORD=morbo
      - MORBO_DB_NAME=morbo
    develop:
      watch:
        - path: .
          action: rebuild
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=morbo
      - POSTGRES_PASSWORD=morbo
      - POSTGRES_DB=morbo
      - PGUSER=morbo
    restart: unless-stopped
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  db:
  traefik:
    external: true
volumes:
  db:
